import './globals.scss';
import { Archivo } from 'next/font/google';
import type { Metadata } from 'next';
import { Footer, Navbar } from './_components';
import 'tailwind-normalize/normalize.css';
// import { nonce } from '@/middleware';

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-fira',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${archivo.className}`}>
      <head>
        <meta name="theme-color" content="#173e56" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="256x256"
          href="/icon-256x256.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="384x384"
          href="/icon-384x384.png"
        />
        <link rel="manifest" href="/mainfest.json" />
      </head>
      <body className="bg-white">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
